-- CREATE DATABASE --
CREATE DATABASE IF NOT EXISTS `QuanLyShowroomOto`;

USE QuanLyShowroomOto;

CREATE TABLE NHACUNGCAP (
    MaNCC VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    TenNCC VARCHAR(50) NOT NULL UNIQUE,
    DiaChi VARCHAR(40),
    SDT VARCHAR(16) NOT NULL UNIQUE
);


CREATE TABLE HANGXE (
    MaHX INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TenHang VARCHAR(20) NOT NULL UNIQUE
);


CREATE TABLE LOAIXE (
    MaLX INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TenLX VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE TENTHONGSO (
    MaTTS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TTS VARCHAR(20) NOT NULL UNIQUE
);


CREATE TABLE XE (
    MaXe VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    TenXe VARCHAR(20) NOT NULL UNIQUE,
    MaLX INT,
    MaHX INT,
    Gia FLOAT NOT NULL,
    SoLuong INT NOT NULL,
    CONSTRAINT `fk XE.MaLX to LOAIXE.MaLX` FOREIGN KEY (MaLX)
        REFERENCES LOAIXE (MaLX),
    CONSTRAINT `fk XE.MaHX to HANGXE.MaHX` FOREIGN KEY (MAHX)
        REFERENCES HANGXE (MaHX)
);

CREATE TABLE GIATRITHONGSO (
    MaGTTS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MaXe VARCHAR(10),
    MaTTS INT,
    GiaTri VARCHAR(20) NOT NULL,
    UNIQUE `unique_index` (MaXe, MaTTS, GiaTri),
    CONSTRAINT `fk GIATRITHONGSO.MaXe to XE.MaXE` FOREIGN KEY (MaXe)
        REFERENCES XE (MaXe),
    CONSTRAINT `fk GIATRITHONGSO.MaTTS to TENTHONGSO.MaTTS` FOREIGN KEY (MaTTS)
        REFERENCES TENTHONGSO (MaTTS)
);

CREATE TABLE PHIEUNHAP (
    MaPN VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    NgayNhap DATE,
    MaNCC VARCHAR(10),
    CONSTRAINT `fk PHIEUNHAP.MaNCC to NHACUNGCAP.MaNCC` FOREIGN KEY (MaNCC)
        REFERENCES NHACUNGCAP (MaNCC)
);

CREATE TABLE CTPHIEUNHAP (
    MaCTPN VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    MaPN VARCHAR(10),
    TenXe VARCHAR(20) NOT NULL,
    LoaiXe VARCHAR(10) NOT NULL,
    HangXe VARCHAR(10) NOT NULL,
    Gia FLOAT NOT NULL,
    SoLuong INT NOT NULL,
    ThanhTien FLOAT NOT NULL,
    CONSTRAINT `fk CTPHIEUNHAP.MaPhieuNhap to PHIEUNHAP.MaPhieuNhap` FOREIGN KEY (MaPN)
        REFERENCES PHIEUNHAP (MaPN)
);

CREATE TABLE THONGSOXENHAP (
    MaTSXN INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MaCTPN VARCHAR(10),
    TenTS VARCHAR(20),
    GiaTri VARCHAR(20) NOT NULL,
    CONSTRAINT `fk THONGSOXENHAP.MaCTPN to CTPHIEUNHAP.MaCTPN` FOREIGN KEY (MaCTPN)
        REFERENCES CTPHIEUNHAP (MaCTPN)
);


CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    TenKH VARCHAR(50),
    SDT VARCHAR(16) UNIQUE,
    Email VARCHAR(100) UNIQUE,
    TongChiTieu FLOAT DEFAULT 0,
    KhachVip BOOLEAN DEFAULT FALSE
);


CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    TenNV VARCHAR(50) NOT NULL,
    DiaChi VARCHAR(100) NOT NULL,
    SDT VARCHAR(16) NOT NULL UNIQUE,
    Email VARCHAR(100) UNIQUE,
    BangCap VARCHAR(10),
    ViTri VARCHAR(20) NOT NULL,
    NgayVL DATE NOT NULL,
    NgaySinh DATE NOT NULL
);

CREATE TABLE HOPDONGDATCOC (
    MaHDDC VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    MaKH VARCHAR(10),
    MaXe VARCHAR(10),
    MaNV VARCHAR(10),
    SoTienDC FLOAT NOT NULL,
    NgayNhanXe DATE NOT NULL,
    CONSTRAINT `fk HOPDONGDATCOC.MaKH to KHACHHANG.MaKH` FOREIGN KEY (MaKH)
        REFERENCES KHACHHANG (MaKH),
    CONSTRAINT `fk HOPDONGDATCOC.MaXe to XE.MaXe` FOREIGN KEY (MaXe)
        REFERENCES XE (MaXe),
    CONSTRAINT `fk HOPDONGDATCOC.MaNV to NHANVIEN.MaNV` FOREIGN KEY (MaNV)
        REFERENCES NHANVIEN (MaNV)
);

CREATE TABLE KHUYENMAI (
    MaKM VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    TenKM VARCHAR(20) UNIQUE,
    PhanTram INT NOT NULL,
    MoTa VARCHAR(200),
    NgayBD DATE NOT NULL,
    NgayKT DATE NOT NULL
);

CREATE TABLE HOPDONGMUAXE (
    MaHDMX VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    MaKH VARCHAR(10),
    MaXe VARCHAR(10),
    MaNV VARCHAR(10),
    NgayKy DATE NOT NULL,
    TongGiaTri FLOAT NOT NULL,
    PTTT VARCHAR(10) NOT NULL,
    MaKM VARCHAR(10),
    CONSTRAINT `fk HOPDONGMUAXE.MaKH to KHACHHANG.MaKH` FOREIGN KEY (MaKH)
        REFERENCES KHACHHANG (MaKH),
    CONSTRAINT `fk HOPDONGMUAXE.MaXe to XE.MaXe` FOREIGN KEY (MaXe)
        REFERENCES XE (MaXe),
    CONSTRAINT `fk HOPDONGMUAXE.MaNV to NHANVIEN.MaNV` FOREIGN KEY (MaNV)
        REFERENCES NHANVIEN (MaNV),
    CONSTRAINT `fk HOPDONGMUAXE.MaKM to KHUYENMAI.MaKM` FOREIGN KEY (MaKM)
        REFERENCES KHUYENMAI (MaKM)
);

CREATE TABLE PHIEUXUAT (
    MaPX VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    MaXe VARCHAR(10),
    NgayXuat DATE NOT NULL,
    CONSTRAINT `fk PHIEUXUAT.MaXe to XE.MaXe` FOREIGN KEY (MaXe)
        REFERENCES XE (MaXe)
);

CREATE TABLE PHIEUBAOHANH (
    MaPBH VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    MaKH VARCHAR(10),
    MaXe VARCHAR(10),
    NgayLap DATE NOT NULL,
    CONSTRAINT `fk PHIEUBAOHANH.MaXe to XE.MaXe` FOREIGN KEY (MaXe)
        REFERENCES XE (MaXe),
    CONSTRAINT `fk PHIEUBAOHANH.MaKH to KHACHHANG.MaKH` FOREIGN KEY (MaKH)
        REFERENCES KHACHHANG (MaKH)
);

CREATE TABLE CTPHIEUBAOHANH (
    MaCTPBH VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    MaPBH VARCHAR(10),
    ThanhPhan VARCHAR(20) NOT NULL,
    MoTaLoi VARCHAR(30),
    CONSTRAINT `fk CTPHIEUBAOHANH.MaPBH to PHIEUBAOHANH.MaPBH` FOREIGN KEY (MaPBH)
        REFERENCES PHIEUBAOHANH (MaPBH)
);

-- Trigger for NHACUNGCAP
DELIMITER $$
CREATE TRIGGER `tg_NHACUNGCAP_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`NHACUNGCAP`
FOR EACH ROW
BEGIN
  -- Set the new MaNCC using an auto-increment value
  SET NEW.`MaNCC` = CONCAT('NCC', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaNCC`, 4) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`NHACUNGCAP`), 4, '0'));
END$$
DELIMITER ;

-- Trigger for XE
DELIMITER $$
CREATE TRIGGER `tg_XE_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`XE`
FOR EACH ROW
BEGIN
  SET NEW.`MaXe` = CONCAT('XE', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaXe`, 3) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`XE`), 4, '0'));
END$$
DELIMITER ;

-- Trigger for PHIEUNHAP
DELIMITER $$
CREATE TRIGGER `tg_PHIEUNHAP_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`PHIEUNHAP`
FOR EACH ROW
BEGIN
  SET NEW.`MaPN` = CONCAT('PN', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaPN`, 3) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`PHIEUNHAP`), 4, '0'));
END$$
DELIMITER ;

-- Trigger for CTPHIEUNHAP
DELIMITER $$
CREATE TRIGGER `tg_CTPHIEUNHAP_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`CTPHIEUNHAP`
FOR EACH ROW
BEGIN
  SET NEW.`MaCTPN` = CONCAT('CTPN', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaCTPN`, 5) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`CTPHIEUNHAP`), 4, '0'));
END$$
DELIMITER ;

-- Trigger for KHACHHANG
DELIMITER $$
CREATE TRIGGER `tg_KHACHHANG_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`KHACHHANG`
FOR EACH ROW
BEGIN
  SET NEW.`MaKH` = CONCAT('KH', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaKH`, 3) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`KHACHHANG`), 4, '0'));
END$$
DELIMITER ;

-- Trigger for NHANVIEN
DELIMITER $$
CREATE TRIGGER `tg_NHANVIEN_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`NHANVIEN`
FOR EACH ROW
BEGIN
  SET NEW.`MaNV` = CONCAT('NV', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaNV`, 3) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`NHANVIEN`), 4, '0'));
END$$
DELIMITER ;

-- Trigger for HOPDONGDATCOC
DELIMITER $$
CREATE TRIGGER `tg_HOPDONGDATCOC_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`HOPDONGDATCOC`
FOR EACH ROW
BEGIN
  SET NEW.`MaHDDC` = CONCAT('HDDC', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaHDDC`, 5) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`HOPDONGDATCOC`), 4, '0'));
END$$
DELIMITER ;

-- Trigger for KHUYENMAI
DELIMITER $$
CREATE TRIGGER `tg_KHUYENMAI_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`KHUYENMAI`
FOR EACH ROW
BEGIN
  SET NEW.`MaKM` = CONCAT('KM', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaKM`, 3) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`KHUYENMAI`), 4, '0'));
END$$
DELIMITER ;

-- Trigger for HOPDONGMUAXE
DELIMITER $$
CREATE TRIGGER `tg_HOPDONGMUAXE_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`HOPDONGMUAXE`
FOR EACH ROW
BEGIN
  SET NEW.`MaHDMX` = CONCAT('HDMX', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaHDMX`, 5) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`HOPDONGMUAXE`), 4, '0'));
END$$
DELIMITER ;

-- Trigger for PHIEUXUAT
DELIMITER $$
CREATE TRIGGER `tg_PHIEUXUAT_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`PHIEUXUAT`
FOR EACH ROW
BEGIN
  SET NEW.`MaPX` = CONCAT('PX', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaPX`, 3) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`PHIEUXUAT`), 4, '0'));
END$$
DELIMITER ;

-- Trigger for PHIEUBAOHANH
DELIMITER $$
CREATE TRIGGER `tg_PHIEUBAOHANH_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`PHIEUBAOHANH`
FOR EACH ROW
BEGIN
  SET NEW.`MaPBH` = CONCAT('PBH', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaPBH`, 4) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`PHIEUBAOHANH`), 4, '0'));
END$$
DELIMITER ;

-- Trigger for CTPHIEUBAOHANH
DELIMITER $$
CREATE TRIGGER `tg_CTPHIEUBAOHANH_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`CTPHIEUBAOHANH`
FOR EACH ROW
BEGIN
  SET NEW.`MaCTPBH` = CONCAT('CTPBH', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaCTPBH`, 6) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`CTPHIEUBAOHANH`), 4, '0'));
END$$
DELIMITER ;

