-- CREATE DATABASE --
CREATE DATABASE IF NOT EXISTS `QuanLyShowroomOto`;

USE QuanLyShowroomOto;

CREATE TABLE `QuanLyShowroomOto`.`NHACUNGCAP` (
	`MaNCC` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`TenNCC` VARCHAR(50) NOT NULL,
	`DiaChi` VARCHAR(40),
	`SDT` VARCHAR(10) NOT NULL
);

CREATE TABLE `QuanLyShowroomOto`.`PHIEUNHAP` (
	`MaPN` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`NgayNhap` DATE,
	`MaNCC` VARCHAR(10),
	CONSTRAINT `fk PHIEUNHAP.MaNCC to NHACUNGCAP.MaNCC` FOREIGN KEY (`MaNCC`) REFERENCES `QuanLyShowroomOto`.`NHACUNGCAP`(`MaNCC`)
);

CREATE TABLE `QuanLyShowroomOto`.`XE` (
	`MaXe` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
    `TenXe` VARCHAR(20) NOT NULL,
	`LoaiXe` VARCHAR(10) NOT NULL,
	`Hang` VARCHAR(10) NOT NULL,
	`Gia` FLOAT NOT NULL,
	`SoLuong` INT NOT NULL,
    `ThongSo` text
);


CREATE TABLE `QuanLyShowroomOto`.`CTPHIEUNHAP` (
	`MaCTPN` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaPN` VARCHAR(10),
	`MaXe` varchar(10) NOT NULL,
  `TenXe` VARCHAR(20) NOT NULL,
	`LoaiXe` VARCHAR(10) NOT NULL,
	`Hang` VARCHAR(10) NOT NULL,
	`Gia` FLOAT NOT NULL,
	`SoLuong` INT NOT NULL,
  `ThongSo` text,
	`ThanhTien` FLOAT NOT NULL,
	CONSTRAINT `fk CTPHIEUNHAP.MaPhieuNhap to PHIEUNHAP.MaPhieuNhap` FOREIGN KEY (`MaPN`) REFERENCES `QuanLyShowroomOto`.`PHIEUNHAP`(`MaPN`),
	CONSTRAINT `fk CTPHIEUNHAP.MaXe to Xe.MaXe` FOREIGN KEY (`MaXe`) REFERENCES `QuanLyShowroomOto`.`XE`(`MaXe`)
);

CREATE TABLE `QuanLyShowroomOto`.`KHACHHANG` (
	`MaKH` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`TenKH` VARCHAR(20),
	`SDT` VARCHAR(10),
	`Email` VARCHAR(20),
	`LoaiKH` VARCHAR(10)
);


CREATE TABLE `QuanLyShowroomOto`.`NHANVIEN` (
	`MaNV` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`TenNV` VARCHAR(20) NOT NULL,
	`DiaChi` VARCHAR(10) NOT NULL,
	`SDT` VARCHAR(10) NOT NULL,
	`Email` VARCHAR(20),
	`BangCap` VARCHAR(10),
	`ViTri` VARCHAR(10) NOT NULL,
	`NgayVL` DATE NOT NULL,
    `NgaySinh` DATE NOT NULL
);

CREATE TABLE `QuanLyShowroomOto`.`HOPDONGDATCOC` (
	`MaHDDC` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaKH` VARCHAR(10),
	`MaXe` varchar(10),
  `MaNV` varchar(10),
	`DieuKien` VARCHAR(40),
	`SoTienDC` FLOAT NOT NULL,
	`NgayNhanXe` DATE NOT NULL,
	CONSTRAINT `fk HOPDONGDATCOC.MaKH to KHACHHANG.MaKH` FOREIGN KEY (`MaKH`) REFERENCES `QuanLyShowroomOto`.`KHACHHANG`(`MaKH`),
	CONSTRAINT `fk HOPDONGDATCOC.MaXe to XE.MaXe` FOREIGN KEY (`MaXe`) REFERENCES `QuanLyShowroomOto`.`XE`(`MaXe`),
  CONSTRAINT `fk HOPDONGDATCOC.MaNV to NHANVIEN.MaNV` FOREIGN KEY (`MaNV`) REFERENCES `QuanLyShowroomOto`.`NHANVIEN`(`MaNV`)
);

CREATE TABLE `QuanLyShowroomOto`.`KHUYENMAI` (
	`MaKM` varchar(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`TenKM` VARCHAR(20),
	`PhanTram` INT NOT NULL,
	`MoTa` VARCHAR(40),
	`NgayBD` DATE NOT NULL,
	`NgayKT` DATE NOT NULL
);

CREATE TABLE `QuanLyShowroomOto`.`HOPDONGMUAXE` (
	`MaHDMX` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaHDDC` VARCHAR(10),
	`NgayKy` DATE NOT NULL,
	`TongGiaTri` FLOAT NOT NULL,
	`PTTT` VARCHAR(10) NOT NULL,
	`MaKM` VARCHAR(10),
	CONSTRAINT `fk HOPDONGMUAXE.MaHDDC to HOPDONGDATCOC.MaHDDC` FOREIGN KEY (MaHDDC) REFERENCES `QuanLyShowroomOto`.`HOPDONGDATCOC`(`MaHDDC`),
	CONSTRAINT `fk HOPDONGMUAXE.MaKM to KHUYENMAI.MaKM` FOREIGN KEY (`MaKM`) REFERENCES `QuanLyShowroomOto`.`KHUYENMAI`(`MaKM`)
);

CREATE TABLE `QuanLyShowroomOto`.`PHIEUXUAT` (
	`MaPX` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaXe` VARCHAR(10),
	`NgayXuat` DATE NOT NULL,
	CONSTRAINT `fk PHIEUXUAT.MaXe to XE.MaXe` FOREIGN KEY (`MaXe`) REFERENCES `QuanLyShowroomOto`.`XE`(`MaXe`)
);

CREATE TABLE `QuanLyShowroomOto`.`PHIEUBAOHANH` (
	`MaPBH` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaKH` VARCHAR(10),
	`MaXe` VARCHAR(10),
	`NgayLap` DATE NOT NULL,
	CONSTRAINT `fk PHIEUBAOHANH.MaXe to XE.MaXe` FOREIGN KEY (`MaXe`) REFERENCES `QuanLyShowroomOto`.`XE`(`MaXe`),
	CONSTRAINT `fk PHIEUBAOHANH.MaKH to KHACHHANG.MaKH` FOREIGN KEY (`MaKH`) REFERENCES `QuanLyShowroomOto`.`KHACHHANG`(`MaKH`)
);

CREATE TABLE `QuanLyShowroomOto`.`CTPHIEUBAOHANH` (
	`MaCTPBH` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaPBH` VARCHAR(10),
	`ThanhPhan` VARCHAR(20) NOT NULL,
	`MoTaLoi` VARCHAR(30),
	CONSTRAINT `fk CTPHIEUBAOHANH.MaPBH to PHIEUBAOHANH.MaPBH` FOREIGN KEY (`MaPBH`) REFERENCES `QuanLyShowroomOto`.`PHIEUBAOHANH`(`MaPBH`)
);

-- Auto-increment sequence for NHACUNGCAP
CREATE TABLE `QuanLyShowroomOto`.`NHACUNGCAP_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for NHACUNGCAP
DELIMITER $$
CREATE TRIGGER `tg_NHACUNGCAP_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`NHACUNGCAP`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`NHACUNGCAP_seq` VALUES (NULL);
  SET NEW.`MaNCC` = CONCAT('NCC', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;

-- Auto-increment sequence for PHIEUNHAP
CREATE TABLE `QuanLyShowroomOto`.`PHIEUNHAP_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for PHIEUNHAP
DELIMITER $$
CREATE TRIGGER `tg_PHIEUNHAP_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`PHIEUNHAP`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`PHIEUNHAP_seq` VALUES (NULL);
  SET NEW.`MaPN` = CONCAT('PN', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;

-- Auto-increment sequence for XE
CREATE TABLE `QuanLyShowroomOto`.`XE_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for XE
DELIMITER $$
CREATE TRIGGER `tg_XE_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`XE`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`XE_seq` VALUES (NULL);
  SET NEW.`MaXe` = CONCAT('XE', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;

-- Auto-increment sequence for CTPHIEUNHAP
CREATE TABLE `QuanLyShowroomOto`.`CTPHIEUNHAP_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for CTPHIEUNHAP
DELIMITER $$
CREATE TRIGGER `tg_CTPHIEUNHAP_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`CTPHIEUNHAP`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`CTPHIEUNHAP_seq` VALUES (NULL);
  SET NEW.`MaCTPN` = CONCAT('CTPN', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;

-- Auto-increment sequence for KHACHHANG
CREATE TABLE `QuanLyShowroomOto`.`KHACHHANG_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for KHACHHANG
DELIMITER $$
CREATE TRIGGER `tg_KHACHHANG_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`KHACHHANG`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`KHACHHANG_seq` VALUES (NULL);
  SET NEW.`MaKH` = CONCAT('KH', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;

-- Auto-increment sequence for NHANVIEN
CREATE TABLE `QuanLyShowroomOto`.`NHANVIEN_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for KHACHHANG
DELIMITER $$
CREATE TRIGGER `tg_NHANVIEN_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`NHANVIEN`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`NHANVIEN_seq` VALUES (NULL);
  SET NEW.`MaNV` = CONCAT('NV', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;


-- Auto-increment sequence for HOPDONGDATCOC
CREATE TABLE `QuanLyShowroomOto`.`HOPDONGDATCOC_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for HOPDONGDATCOC
DELIMITER $$
CREATE TRIGGER `tg_HOPDONGDATCOC_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`HOPDONGDATCOC`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`HOPDONGDATCOC_seq` VALUES (NULL);
  SET NEW.`MaHDDC` = CONCAT('HDDC', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;

-- Auto-increment sequence for KHUYENMAI
CREATE TABLE `QuanLyShowroomOto`.`KHUYENMAI_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for KHUYENMAI
DELIMITER $$
CREATE TRIGGER `tg_KHUYENMAI_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`KHUYENMAI`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`KHUYENMAI_seq` VALUES (NULL);
  SET NEW.`MaKM` = CONCAT('KM', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;

-- Auto-increment sequence for HOPDONGMUAXE
CREATE TABLE `QuanLyShowroomOto`.`HOPDONGMUAXE_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for HOPDONGMUAXE
DELIMITER $$
CREATE TRIGGER `tg_HOPDONGMUAXE_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`HOPDONGMUAXE`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`HOPDONGMUAXE_seq` VALUES (NULL);
  SET NEW.`MaHDMX` = CONCAT('HDMX', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;

-- Auto-increment sequence for PHIEUXUAT
CREATE TABLE `QuanLyShowroomOto`.`PHIEUXUAT_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for PHIEUXUAT
DELIMITER $$
CREATE TRIGGER `tg_PHIEUXUAT_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`PHIEUXUAT`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`PHIEUXUAT_seq` VALUES (NULL);
  SET NEW.`MaPX` = CONCAT('PX', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;

-- Auto-increment sequence for PHIEUBAOHANH
CREATE TABLE `QuanLyShowroomOto`.`PHIEUBAOHANH_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for PHIEUBAOHANH
DELIMITER $$
CREATE TRIGGER `tg_PHIEUBAOHANH_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`PHIEUBAOHANH`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`PHIEUBAOHANH_seq` VALUES (NULL);
  SET NEW.`MaPBH` = CONCAT('PBH', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;

-- Auto-increment sequence for CTPHIEUBAOHANH
CREATE TABLE `QuanLyShowroomOto`.`CTPHIEUBAOHANH_seq`
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

-- Trigger for CTPHIEUBAOHANH
DELIMITER $$
CREATE TRIGGER `tg_CTPHIEUBAOHANH_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`CTPHIEUBAOHANH`
FOR EACH ROW
BEGIN
  INSERT INTO `QuanLyShowroomOto`.`CTPHIEUBAOHANH_seq` VALUES (NULL);
  SET NEW.`MaCTPBH` = CONCAT('CTPBH', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;


-- INSERT STATEMENTS --
INSERT INTO NHACUNGCAP (TenNCC, DiaChi, SDT)
VALUES ('Nhà cung cấp A', 'Địa chỉ A', '0123456789');

INSERT INTO NHACUNGCAP (TenNCC, DiaChi, SDT)
VALUES ('Nhà cung cấp B', 'Địa chỉ B', '0987654321');

INSERT INTO PHIEUNHAP (NgayNhap, MaNCC)
VALUES ('2023-01-01', 'NCC001');

INSERT INTO PHIEUNHAP (NgayNhap, MaNCC)
VALUES ('2023-02-01', 'NCC002');

INSERT INTO XE (TenXe, LoaiXe, Hang, Gia, SoLuong, ThongSo)
VALUES ('Xe A', 'Sedan', 'Honda', 50000, 10, 'Thông số A');

INSERT INTO XE (TenXe, LoaiXe, Hang, Gia, SoLuong, ThongSo)
VALUES ('Xe B', 'SUV', 'Toyota', 60000, 8, 'Thông số B');

INSERT INTO KHACHHANG (TenKH, SDT, Email, LoaiKH)
VALUES ('Khách hàng A', '0123456789', 'khachA@email.com', 'Loại A');

INSERT INTO KHACHHANG (TenKH, SDT, Email, LoaiKH)
VALUES ('Khách hàng B', '0987654321', 'khachB@email.com', 'Loại B');

