-- CREATE DATABASE --
CREATE DATABASE IF NOT EXISTS `QuanLyShowroomOto`;

USE QuanLyShowroomOto;

CREATE TABLE `QuanLyShowroomOto`.`NHACUNGCAP` (
	`MaNCC` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`TenNCC` VARCHAR(50) NOT NULL UNIQUE,
	`DiaChi` VARCHAR(40),
	`SDT` VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE `QuanLyShowroomOto`.`PHIEUNHAP` (
	`MaPN` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`NgayNhap` DATE,
	`MaNCC` VARCHAR(10),
	CONSTRAINT `fk PHIEUNHAP.MaNCC to NHACUNGCAP.MaNCC` FOREIGN KEY (`MaNCC`) REFERENCES `QuanLyShowroomOto`.`NHACUNGCAP`(`MaNCC`)
);

CREATE TABLE `QuanLyShowroomOto`.`XE` (
	`MaXe` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
  `TenXe` VARCHAR(20) NOT NULL UNIQUE,
	`LoaiXe` VARCHAR(10) NOT NULL,
	`Hang` VARCHAR(10) NOT NULL,
	`Gia` FLOAT NOT NULL,
	`SoLuong` INT NOT NULL,
    `ThongSo` text
);


CREATE TABLE `QuanLyShowroomOto`.`CTPHIEUNHAP` (
	`MaCTPN` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaPN` VARCHAR(10),
	`MaXe` varchar(10) NOT NULL,
  `TenXe` VARCHAR(20) NOT NULL,
	`LoaiXe` VARCHAR(10) NOT NULL,
	`Hang` VARCHAR(10) NOT NULL,
	`Gia` FLOAT NOT NULL,
	`SoLuong` INT NOT NULL,
  `ThongSo` text,
	`ThanhTien` FLOAT NOT NULL,
	CONSTRAINT `fk CTPHIEUNHAP.MaPhieuNhap to PHIEUNHAP.MaPhieuNhap` FOREIGN KEY (`MaPN`) REFERENCES `QuanLyShowroomOto`.`PHIEUNHAP`(`MaPN`),
	CONSTRAINT `fk CTPHIEUNHAP.MaXe to Xe.MaXe` FOREIGN KEY (`MaXe`) REFERENCES `QuanLyShowroomOto`.`XE`(`MaXe`)
);

CREATE TABLE `QuanLyShowroomOto`.`KHACHHANG` (
	`MaKH` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`TenKH` VARCHAR(20),
	`SDT` VARCHAR(10) UNIQUE,
	`Email` VARCHAR(20) UNIQUE,
	`LoaiKH` VARCHAR(10)
);


CREATE TABLE `QuanLyShowroomOto`.`NHANVIEN` (
	`MaNV` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`TenNV` VARCHAR(20) NOT NULL,
	`DiaChi` VARCHAR(10) NOT NULL,
	`SDT` VARCHAR(10) NOT NULL UNIQUE,
	`Email` VARCHAR(20) UNIQUE,
	`BangCap` VARCHAR(10),
	`ViTri` VARCHAR(10) NOT NULL,
	`NgayVL` DATE NOT NULL,
  `NgaySinh` DATE NOT NULL
);

CREATE TABLE `QuanLyShowroomOto`.`HOPDONGDATCOC` (
	`MaHDDC` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaKH` VARCHAR(10),
	`MaXe` varchar(10),
  `MaNV` varchar(10),
	`DieuKien` VARCHAR(40),
	`SoTienDC` FLOAT NOT NULL,
	`NgayNhanXe` DATE NOT NULL,
	CONSTRAINT `fk HOPDONGDATCOC.MaKH to KHACHHANG.MaKH` FOREIGN KEY (`MaKH`) REFERENCES `QuanLyShowroomOto`.`KHACHHANG`(`MaKH`),
	CONSTRAINT `fk HOPDONGDATCOC.MaXe to XE.MaXe` FOREIGN KEY (`MaXe`) REFERENCES `QuanLyShowroomOto`.`XE`(`MaXe`),
  CONSTRAINT `fk HOPDONGDATCOC.MaNV to NHANVIEN.MaNV` FOREIGN KEY (`MaNV`) REFERENCES `QuanLyShowroomOto`.`NHANVIEN`(`MaNV`)
);

CREATE TABLE `QuanLyShowroomOto`.`KHUYENMAI` (
	`MaKM` varchar(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`TenKM` VARCHAR(20) UNIQUE,
	`PhanTram` INT NOT NULL,
	`MoTa` VARCHAR(40),
	`NgayBD` DATE NOT NULL,
	`NgayKT` DATE NOT NULL
);

CREATE TABLE `QuanLyShowroomOto`.`HOPDONGMUAXE` (
	`MaHDMX` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaHDDC` VARCHAR(10),
	`NgayKy` DATE NOT NULL,
	`TongGiaTri` FLOAT NOT NULL,
	`PTTT` VARCHAR(10) NOT NULL,
	`MaKM` VARCHAR(10),
	CONSTRAINT `fk HOPDONGMUAXE.MaHDDC to HOPDONGDATCOC.MaHDDC` FOREIGN KEY (MaHDDC) REFERENCES `QuanLyShowroomOto`.`HOPDONGDATCOC`(`MaHDDC`),
	CONSTRAINT `fk HOPDONGMUAXE.MaKM to KHUYENMAI.MaKM` FOREIGN KEY (`MaKM`) REFERENCES `QuanLyShowroomOto`.`KHUYENMAI`(`MaKM`)
);

CREATE TABLE `QuanLyShowroomOto`.`PHIEUXUAT` (
	`MaPX` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaXe` VARCHAR(10),
	`NgayXuat` DATE NOT NULL,
	CONSTRAINT `fk PHIEUXUAT.MaXe to XE.MaXe` FOREIGN KEY (`MaXe`) REFERENCES `QuanLyShowroomOto`.`XE`(`MaXe`)
);

CREATE TABLE `QuanLyShowroomOto`.`PHIEUBAOHANH` (
	`MaPBH` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaKH` VARCHAR(10),
	`MaXe` VARCHAR(10),
	`NgayLap` DATE NOT NULL,
	CONSTRAINT `fk PHIEUBAOHANH.MaXe to XE.MaXe` FOREIGN KEY (`MaXe`) REFERENCES `QuanLyShowroomOto`.`XE`(`MaXe`),
	CONSTRAINT `fk PHIEUBAOHANH.MaKH to KHACHHANG.MaKH` FOREIGN KEY (`MaKH`) REFERENCES `QuanLyShowroomOto`.`KHACHHANG`(`MaKH`)
);

CREATE TABLE `QuanLyShowroomOto`.`CTPHIEUBAOHANH` (
	`MaCTPBH` VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT '0',
	`MaPBH` VARCHAR(10),
	`ThanhPhan` VARCHAR(20) NOT NULL,
	`MoTaLoi` VARCHAR(30),
	CONSTRAINT `fk CTPHIEUBAOHANH.MaPBH to PHIEUBAOHANH.MaPBH` FOREIGN KEY (`MaPBH`) REFERENCES `QuanLyShowroomOto`.`PHIEUBAOHANH`(`MaPBH`)
);


-- Trigger for NHACUNGCAP
DELIMITER $$
CREATE TRIGGER `tg_NHACUNGCAP_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`NHACUNGCAP`
FOR EACH ROW
BEGIN
  -- Set the new MaNCC using an auto-increment value
  SET NEW.`MaNCC` = CONCAT('NCC', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaNCC`, 4) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`NHACUNGCAP`), 3, '0'));
END$$
DELIMITER ;

-- Trigger for XE
DELIMITER $$
CREATE TRIGGER `tg_XE_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`XE`
FOR EACH ROW
BEGIN
  SET NEW.`MaXe` = CONCAT('XE', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaXe`, 4) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`XE`), 3, '0'));
END$$
DELIMITER ;

-- Trigger for PHIEUNHAP
DELIMITER $$
CREATE TRIGGER `tg_PHIEUNHAP_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`PHIEUNHAP`
FOR EACH ROW
BEGIN
  SET NEW.`MaPN` = CONCAT('PN', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaPN`, 4) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`PHIEUNHAP`), 3, '0'));
END$$
DELIMITER ;

-- Trigger for CTPHIEUNHAP
DELIMITER $$
CREATE TRIGGER `tg_CTPHIEUNHAP_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`CTPHIEUNHAP`
FOR EACH ROW
BEGIN
  SET NEW.`MaCTPN` = CONCAT('CTPN', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaCTPN`, 5) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`CTPHIEUNHAP`), 3, '0'));
END$$
DELIMITER ;

-- Trigger for KHACHHANG
DELIMITER $$
CREATE TRIGGER `tg_KHACHHANG_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`KHACHHANG`
FOR EACH ROW
BEGIN
  SET NEW.`MaKH` = CONCAT('KH', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaKH`, 3) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`KHACHHANG`), 3, '0'));
END$$
DELIMITER ;

-- Trigger for NHANVIEN
DELIMITER $$
CREATE TRIGGER `tg_NHANVIEN_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`NHANVIEN`
FOR EACH ROW
BEGIN
  SET NEW.`MaNV` = CONCAT('NV', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaNV`, 3) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`NHANVIEN`), 3, '0'));
END$$
DELIMITER ;

-- Trigger for HOPDONGDATCOC
DELIMITER $$
CREATE TRIGGER `tg_HOPDONGDATCOC_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`HOPDONGDATCOC`
FOR EACH ROW
BEGIN
  SET NEW.`MaHDDC` = CONCAT('HDDC', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaHDDC`, 5) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`HOPDONGDATCOC`), 3, '0'));
END$$
DELIMITER ;

-- Trigger for KHUYENMAI
DELIMITER $$
CREATE TRIGGER `tg_KHUYENMAI_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`KHUYENMAI`
FOR EACH ROW
BEGIN
  SET NEW.`MaKM` = CONCAT('KM', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaKM`, 3) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`KHUYENMAI`), 3, '0'));
END$$
DELIMITER ;

-- Trigger for HOPDONGMUAXE
DELIMITER $$
CREATE TRIGGER `tg_HOPDONGMUAXE_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`HOPDONGMUAXE`
FOR EACH ROW
BEGIN
  SET NEW.`MaHDMX` = CONCAT('HDMX', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaHDMX`, 5) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`HOPDONGMUAXE`), 3, '0'));
END$$
DELIMITER ;

-- Trigger for PHIEUXUAT
DELIMITER $$
CREATE TRIGGER `tg_PHIEUXUAT_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`PHIEUXUAT`
FOR EACH ROW
BEGIN
  SET NEW.`MaPX` = CONCAT('PX', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaPX`, 3) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`PHIEUXUAT`), 3, '0'));
END$$
DELIMITER ;

-- Trigger for PHIEUBAOHANH
DELIMITER $$
CREATE TRIGGER `tg_PHIEUBAOHANH_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`PHIEUBAOHANH`
FOR EACH ROW
BEGIN
  SET NEW.`MaPBH` = CONCAT('PBH', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaPBH`, 4) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`PHIEUBAOHANH`), 3, '0'));
END$$
DELIMITER ;

-- Trigger for CTPHIEUBAOHANH
DELIMITER $$
CREATE TRIGGER `tg_CTPHIEUBAOHANH_insert`
BEFORE INSERT ON `QuanLyShowroomOto`.`CTPHIEUBAOHANH`
FOR EACH ROW
BEGIN
  SET NEW.`MaCTPBH` = CONCAT('CTPBH', LPAD((SELECT IFNULL(MAX(CAST(SUBSTRING(`MaCTPBH`, 6) AS SIGNED)), 0) + 1 FROM `QuanLyShowroomOto`.`CTPHIEUBAOHANH`), 3, '0'));
END$$
DELIMITER ;



SELECT * FROM ctphieubaohanh c;
SELECT * FROM ctphieunhap c;
SELECT * FROM hopdongdatcoc h;
SELECT * FROM hopdongmuaxe h;
SELECT * FROM khachhang k;
SELECT * FROM khuyenmai k;
SELECT * FROM nhacungcap n;
SELECT * FROM nhanvien n;
SELECT * FROM phieubaohanh p;
SELECT * FROM phieunhap p;
SELECT * FROM phieuxuat p;
SELECT * FROM xe x; 

-- INSERT STATEMENTS --
INSERT INTO NHACUNGCAP (TenNCC, DiaChi, SDT)
VALUES ('Nhà cung cấp A', 'Địa chỉ A', '0123456789');

INSERT INTO NHACUNGCAP (TenNCC, DiaChi, SDT)
VALUES ('Nhà cung cấp B', 'Địa chỉ B', '0987654321');

INSERT INTO NHACUNGCAP (TenNCC, DiaChi, SDT)
VALUES ('Nhà cung cấp C', 'Địa chỉ B', '0987654322');

INSERT INTO PHIEUNHAP (NgayNhap, MaNCC)
VALUES ('2023-01-01', 'NCC001');

INSERT INTO PHIEUNHAP (NgayNhap, MaNCC)
VALUES ('2023-02-01', 'NCC002');

INSERT INTO XE (TenXe, LoaiXe, Hang, Gia, SoLuong, ThongSo)
VALUES ('Xe A', 'Sedan', 'Honda', 50000, 10, 'Thông số A');

INSERT INTO XE (TenXe, LoaiXe, Hang, Gia, SoLuong, ThongSo)
VALUES ('Xe B', 'SUV', 'Toyota', 60000, 8, 'Thông số B');

INSERT INTO KHACHHANG (TenKH, SDT, Email, LoaiKH)
VALUES ('Khách hàng A', '0123456789', 'khachA@email.com', 'Loại A');

INSERT INTO KHACHHANG (TenKH, SDT, Email, LoaiKH)
VALUES ('Khách hàng B', '0987654321', 'khachB@email.com', 'Loại B');

